"""Internal module for the Codex GitHub review agent."""

from __future__ import annotations

import argparse
import contextlib
import dataclasses
import datetime as dt
import fcntl
import hashlib
import json
import logging
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
from collections.abc import Iterator, Sequence
from pathlib import Path
from typing import Any

from .core import *
from .models import *
from .github import *
from .storage import *
from .reviews import *

def same_revision(left: PullRequest, right: PullRequest) -> bool:
    return left.key == right.key and left.fingerprint == right.fingerprint


def same_issue_revision(left: Issue, right: Issue) -> bool:
    return left.key == right.key and left.fingerprint == right.fingerprint


def fetch_pull_request(
    runner: CommandRunner,
    *,
    gh_bin: str,
    org: str,
    mention: str,
    repo_full_name: str,
    number: int,
    repositories: Sequence[str] = (),
) -> PullRequest | None:
    payload = runner.json([gh_bin, "api", f"repos/{repo_full_name}/pulls/{number}"])
    if not isinstance(payload, dict):
        raise AgentError(
            f"GitHub returned invalid metadata for {repo_full_name}#{number}"
        )
    pull_request = parse_pull_request(payload, org, mention)
    if pull_request is not None and not repository_is_selected(
        pull_request.repo_full_name, repositories
    ):
        return None
    if pull_request is None:
        return None
    return dataclasses.replace(
        pull_request,
        base_sha=fetch_pull_request_base_sha(
            runner, gh_bin=gh_bin, pull_request=pull_request
        ),
    )


def render_review_comment(
    pull_request: PullRequest,
    result: ReviewResult,
    *,
    agent_name: str = DEFAULT_AGENT_NAME,
    marker: str = DEFAULT_MARKER,
) -> str:
    label = "APPROVED" if result.verdict == "approved" else "CHANGES REQUESTED"
    body = result.review_body or "Review completed."
    marker = (
        f"<!-- {marker}:v1 "
        f"repo={pull_request.repo_full_name} pr={pull_request.number} "
        f"base={pull_request.base_sha} head={pull_request.head_sha} "
        f"body={pull_request.body_sha256} verdict={result.verdict} -->"
    )
    return (
        f"## {agent_name} review — {label}\n\n"
        f"Exact head: `{pull_request.head_sha}`  \n"
        f"Base: `{pull_request.base_sha}`\n\n"
        f"{result.summary}\n\n{body}\n\n"
        f"_Generated by Codex using the continuing {agent_name} review thread._\n\n"
        f"{marker}\n"
    )


def render_issue_review_comment(
    issue: Issue,
    result: ReviewResult,
    *,
    agent_name: str = DEFAULT_AGENT_NAME,
    marker: str = DEFAULT_MARKER,
) -> str:
    label = "APPROVED" if result.verdict == "approved" else "CHANGES REQUESTED"
    body = result.review_body or "No blocking findings."
    request_token = (
        "body" if issue.request_comment_id is None else str(issue.request_comment_id)
    )
    marker = (
        f"<!-- {marker}:v1 kind=issue "
        f"repo={issue.repo_full_name} issue={issue.number} "
        f"code={issue.code_sha} body={issue.body_sha256} "
        f"request={request_token} request_body={issue.request_body_sha256} "
        f"verdict={result.verdict} -->"
    )
    return (
        f"## {agent_name} Issue review — {label}\n\n"
        f"Exact Issue body: `{issue.body_sha256}`  \n"
        f"Code anchor: `{issue.code_ref}@{issue.code_sha}`\n\n"
        f"{result.summary}\n\n{body}\n\n"
        f"_Generated by Codex using the continuing {agent_name} review thread._\n\n"
        f"{marker}\n"
    )


def publish_review_comment(
    runner: CommandRunner,
    *,
    gh_bin: str,
    pull_request: PullRequest,
    result: ReviewResult,
    state_dir: Path,
    agent_name: str = DEFAULT_AGENT_NAME,
    marker: str = DEFAULT_MARKER,
) -> str:
    temp_dir = state_dir / "tmp"
    temp_dir.mkdir(parents=True, exist_ok=True)
    file_descriptor, body_name = tempfile.mkstemp(
        prefix="review-comment-", suffix=".md", dir=temp_dir
    )
    body_path = Path(body_name)
    try:
        with os.fdopen(file_descriptor, "w", encoding="utf-8") as handle:
            handle.write(
                render_review_comment(
                    pull_request, result, agent_name=agent_name, marker=marker
                )
            )
            handle.flush()
            os.fsync(handle.fileno())
        completed = runner.run(
            [
                gh_bin,
                "pr",
                "comment",
                str(pull_request.number),
                "--repo",
                pull_request.repo_full_name,
                "--body-file",
                str(body_path),
            ]
        )
        return completed.stdout.strip()
    finally:
        with contextlib.suppress(OSError):
            body_path.unlink()


def publish_issue_review_comment(
    runner: CommandRunner,
    *,
    gh_bin: str,
    issue: Issue,
    result: ReviewResult,
    state_dir: Path,
    agent_name: str = DEFAULT_AGENT_NAME,
    marker: str = DEFAULT_MARKER,
) -> str:
    temp_dir = state_dir / "tmp"
    temp_dir.mkdir(parents=True, exist_ok=True)
    file_descriptor, body_name = tempfile.mkstemp(
        prefix="issue-review-comment-", suffix=".md", dir=temp_dir
    )
    body_path = Path(body_name)
    try:
        with os.fdopen(file_descriptor, "w", encoding="utf-8") as handle:
            handle.write(
                render_issue_review_comment(
                    issue, result, agent_name=agent_name, marker=marker
                )
            )
            handle.flush()
            os.fsync(handle.fileno())
        completed = runner.run(
            [
                gh_bin,
                "issue",
                "comment",
                str(issue.number),
                "--repo",
                issue.repo_full_name,
                "--body-file",
                str(body_path),
            ]
        )
        return completed.stdout.strip()
    finally:
        with contextlib.suppress(OSError):
            body_path.unlink()


def record_review(
    state: dict[str, Any],
    pull_request: PullRequest,
    result: ReviewResult,
    review_url: str,
) -> None:
    state["pull_requests"][pull_request.key] = {
        **pull_request.fingerprint,
        "verdict": result.verdict,
        "review_url": review_url,
        "reviewed_at": utc_now(),
        **({"sweep": result.sweep} if result.sweep is not None else {}),
    }


def record_issue_review(
    state: dict[str, Any],
    issue: Issue,
    result: ReviewResult,
    review_url: str,
) -> None:
    issues = state.setdefault("issues", {})
    if not isinstance(issues, dict):
        raise AgentError("issue state is malformed")
    issues[issue.key] = {
        **issue.fingerprint,
        "verdict": result.verdict,
        "review_url": review_url,
        "reviewed_at": utc_now(),
        **({"sweep": result.sweep} if result.sweep is not None else {}),
    }


@dataclasses.dataclass(frozen=True)
class Config:
    org: str
    repositories: tuple[str, ...]
    mention: str
    agent_name: str
    marker: str
    issue_branch: str | None
    review_context: str
    session_id: str | None
    interval: int
    once: bool
    dry_run: bool
    state_dir: Path
    worktree_root: Path
    codex_timeout: int
    issue_codex_timeout: int
    gh_bin: str
    codex_bin: str
    codex_bypass_sandbox: bool


def process_cycle(
    config: Config,
    runner: CommandRunner,
    store: StateStore,
    state: dict[str, Any],
) -> bool:
    pull_requests = discover_pull_requests(
        runner,
        gh_bin=config.gh_bin,
        org=config.org,
        mention=config.mention,
        repositories=config.repositories,
    )
    LOG.info(
        "found %d open, non-draft pull request(s) with %s",
        len(pull_requests),
        config.mention,
    )
    issue_discovery_succeeded = True
    try:
        issues = discover_issues(
            runner,
            gh_bin=config.gh_bin,
            org=config.org,
            mention=config.mention,
            preferred_branch=config.issue_branch,
            marker=config.marker,
            agent_name=config.agent_name,
            repositories=config.repositories,
        )
    except TransientNetworkError as exc:
        issue_discovery_succeeded = False
        issues = []
        LOG.warning(
            "Issue discovery remains pending after network retries: %s",
            exc,
        )
    except AgentError as exc:
        issue_discovery_succeeded = False
        issues = []
        LOG.error("Issue discovery failed: %s", exc)
    LOG.info("found %d open Issue(s) with %s", len(issues), config.mention)
    workspace = RepositoryWorkspace(
        runner,
        gh_bin=config.gh_bin,
        state_dir=config.state_dir,
        worktree_root=config.worktree_root,
    )
    successful = issue_discovery_succeeded

    for pull_request in pull_requests:
        if not needs_review(state, pull_request):
            LOG.info(
                "up to date: %s at %s", pull_request.key, pull_request.head_sha[:12]
            )
            continue
        if config.dry_run:
            LOG.info("would review: %s %s", pull_request.key, pull_request.url)
            continue
        if config.session_id is None:
            raise AgentError("--session-id or REVIEW_SESSION_ID is required")

        LOG.info("reviewing: %s at %s", pull_request.key, pull_request.head_sha[:12])
        try:
            with workspace.checkout(pull_request) as worktree:
                result = run_codex_review(
                    runner,
                    codex_bin=config.codex_bin,
                    session_id=config.session_id,
                    worktree=worktree,
                    pull_request=pull_request,
                    state_dir=config.state_dir,
                    timeout=config.codex_timeout,
                    review_context=config.review_context,
                    bypass_sandbox=config.codex_bypass_sandbox,
                )
            if result.verdict in {"superseded", "error"}:
                LOG.warning(
                    "Codex returned %s for %s: %s",
                    result.verdict,
                    pull_request.key,
                    result.summary,
                )
                successful = False
                continue

            current = fetch_pull_request(
                runner,
                gh_bin=config.gh_bin,
                org=config.org,
                mention=config.mention,
                repo_full_name=pull_request.repo_full_name,
                number=pull_request.number,
                repositories=config.repositories,
            )
            if current is None or not same_revision(pull_request, current):
                LOG.warning(
                    "%s changed before publication; discarding stale result",
                    pull_request.key,
                )
                successful = False
                continue

            review_url = publish_review_comment(
                runner,
                gh_bin=config.gh_bin,
                pull_request=pull_request,
                result=result,
                state_dir=config.state_dir,
                agent_name=config.agent_name,
                marker=config.marker,
            )
            record_review(state, pull_request, result, review_url)
            store.save(state)
            LOG.info(
                "published %s for %s%s",
                result.verdict,
                pull_request.key,
                f": {review_url}" if review_url else "",
            )
        except TransientNetworkError as exc:
            successful = False
            LOG.warning(
                "network unavailable for %s after retries; revision remains pending "
                "for the next poll: %s",
                pull_request.key,
                exc,
            )
        except AgentError as exc:
            successful = False
            LOG.error("review failed for %s: %s", pull_request.key, exc)

    for issue in issues:
        if not needs_issue_review(state, issue):
            LOG.info("up to date: Issue %s body %s", issue.key, issue.body_sha256[:12])
            continue
        if config.dry_run:
            LOG.info("would review Issue: %s %s", issue.key, issue.url)
            continue
        if config.session_id is None:
            raise AgentError("--session-id or REVIEW_SESSION_ID is required")

        LOG.info(
            "reviewing Issue: %s body %s at %s",
            issue.key,
            issue.body_sha256[:12],
            issue.code_sha[:12],
        )
        try:
            with workspace.checkout_issue(issue) as worktree:
                result = run_codex_issue_review(
                    runner,
                    codex_bin=config.codex_bin,
                    session_id=config.session_id,
                    worktree=worktree,
                    issue=issue,
                    state_dir=config.state_dir,
                    timeout=config.issue_codex_timeout,
                    review_context=config.review_context,
                    bypass_sandbox=config.codex_bypass_sandbox,
                )
            if result.verdict in {"superseded", "error"}:
                LOG.warning(
                    "Codex returned %s for Issue %s: %s",
                    result.verdict,
                    issue.key,
                    result.summary,
                )
                successful = False
                continue

            current = fetch_issue(
                runner,
                gh_bin=config.gh_bin,
                org=config.org,
                mention=config.mention,
                repo_full_name=issue.repo_full_name,
                number=issue.number,
                preferred_branch=config.issue_branch,
                marker=config.marker,
                agent_name=config.agent_name,
                repositories=config.repositories,
            )
            if (
                current is None
                or current.has_matching_review
                or not same_issue_revision(issue, current)
            ):
                LOG.warning(
                    "Issue %s changed before publication; discarding stale result",
                    issue.key,
                )
                successful = False
                continue

            review_url = publish_issue_review_comment(
                runner,
                gh_bin=config.gh_bin,
                issue=issue,
                result=result,
                state_dir=config.state_dir,
                agent_name=config.agent_name,
                marker=config.marker,
            )
            record_issue_review(state, issue, result, review_url)
            store.save(state)
            LOG.info(
                "published %s for Issue %s%s",
                result.verdict,
                issue.key,
                f": {review_url}" if review_url else "",
            )
        except TransientNetworkError as exc:
            successful = False
            LOG.warning(
                "network unavailable for Issue %s after retries; request remains "
                "pending for the next poll: %s",
                issue.key,
                exc,
            )
        except AgentError as exc:
            successful = False
            LOG.error("Issue review failed for %s: %s", issue.key, exc)
    return successful


def parse_args(argv: Sequence[str] | None = None) -> Config:
    try:
        load_dotenv(APP_ROOT / ".env")
    except AgentError as exc:
        raise SystemExit(str(exc)) from exc
    parser = argparse.ArgumentParser(
        description=(
            "Poll open GitHub PRs and Issues for a configured mention, resume one Codex "
            "session, and publish revision-scoped review comments."
        )
    )
    parser.add_argument("--org", default=os.environ.get("REVIEW_ORG"))
    parser.add_argument(
        "--repo",
        action="append",
        default=None,
        help="repository to monitor (repeatable; accepts repo or org/repo, and comma-separated values)",
    )
    parser.add_argument(
        "--mention", default=os.environ.get("REVIEW_MENTION", "@codex-review")
    )
    parser.add_argument(
        "--agent-name", default=os.environ.get("REVIEW_AGENT_NAME", DEFAULT_AGENT_NAME)
    )
    parser.add_argument(
        "--marker", default=os.environ.get("REVIEW_MARKER", DEFAULT_MARKER)
    )
    parser.add_argument(
        "--issue-branch",
        default=os.environ.get("REVIEW_ISSUE_BRANCH") or None,
        help="preferred Issue code anchor; defaults to each repository's default branch",
    )
    parser.add_argument(
        "--review-context",
        default=os.environ.get("REVIEW_CONTEXT", DEFAULT_REVIEW_CONTEXT),
        help="additional scope sent to Codex for every review",
    )
    parser.add_argument(
        "--session-id",
        default=os.environ.get("REVIEW_SESSION_ID")
        or os.environ.get("CODEX_THREAD_ID"),
        help=(
            "Codex session to resume (default: REVIEW_SESSION_ID, then CODEX_THREAD_ID)"
        ),
    )
    parser.add_argument(
        "--interval",
        type=int,
        default=int(os.environ.get("REVIEW_INTERVAL", "120")),
        help="poll interval in seconds",
    )
    parser.add_argument(
        "--once", action="store_true", help="run one polling cycle and exit"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="discover and report work without cloning, invoking Codex, or commenting",
    )
    parser.add_argument(
        "--state-dir",
        type=Path,
        default=Path(os.environ.get("REVIEW_STATE_DIR", DEFAULT_STATE_DIR)),
    )
    parser.add_argument(
        "--worktree-root",
        type=Path,
        default=Path(os.environ.get("REVIEW_WORKTREE_ROOT", DEFAULT_WORKTREE_ROOT)),
    )
    parser.add_argument(
        "--codex-timeout",
        type=int,
        default=int(os.environ.get("REVIEW_CODEX_TIMEOUT", "720")),
        help="maximum seconds for the PR product review",
    )
    parser.add_argument(
        "--approval-check-timeout",
        type=int,
        default=300,
        help="deprecated compatibility option; approval check has been removed",
    )
    parser.add_argument(
        "--issue-codex-timeout",
        type=int,
        default=int(os.environ.get("REVIEW_ISSUE_CODEX_TIMEOUT", "600")),
        help="maximum seconds for the single Issue workflow/contract review",
    )
    parser.add_argument(
        "--max-review-passes",
        type=int,
        default=2,
        help="deprecated compatibility option; PR review now uses one pass",
    )
    parser.add_argument("--gh-bin", default=os.environ.get("REVIEW_GH_BIN", "gh"))
    parser.add_argument(
        "--codex-bin", default=os.environ.get("REVIEW_CODEX_BIN", "codex")
    )
    parser.add_argument(
        "--codex-bypass-sandbox",
        action=argparse.BooleanOptionalAction,
        default=env_flag("REVIEW_CODEX_BYPASS_SANDBOX"),
        help="run Codex without its approval and sandbox protections (trusted hosts only)",
    )
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args(argv)
    if not args.org or not args.org.strip():
        parser.error("--org or REVIEW_ORG is required")
    try:
        repositories = normalize_repositories(
            args.repo if args.repo is not None else [os.environ.get("REVIEW_REPOS", "")],
            args.org,
        )
    except ValueError as exc:
        parser.error(str(exc))
    if args.interval <= 0:
        parser.error("--interval must be positive")
    if args.codex_timeout <= 0:
        parser.error("--codex-timeout must be positive")
    if args.issue_codex_timeout <= 0:
        parser.error("--issue-codex-timeout must be positive")
    if not args.dry_run and not args.session_id:
        parser.error(
            "--session-id or REVIEW_SESSION_ID is required unless --dry-run is used"
        )
    try:
        contains_exact_mention("", args.mention)
    except ValueError as exc:
        parser.error(str(exc))
    if not args.agent_name.strip():
        parser.error("--agent-name must not be empty")
    if SAFE_COMPONENT_RE.fullmatch(args.marker) is None:
        parser.error("--marker must contain only letters, numbers, dot, underscore, or hyphen")
    if not args.review_context.strip():
        parser.error("--review-context must not be empty")

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
        datefmt="%Y-%m-%dT%H:%M:%SZ",
    )
    logging.Formatter.converter = time.gmtime
    return Config(
        org=args.org,
        repositories=repositories,
        mention=args.mention,
        agent_name=args.agent_name.strip(),
        marker=args.marker,
        issue_branch=args.issue_branch,
        review_context=args.review_context.strip(),
        session_id=args.session_id,
        interval=args.interval,
        once=args.once,
        dry_run=args.dry_run,
        state_dir=args.state_dir.resolve(),
        worktree_root=args.worktree_root.resolve(),
        codex_timeout=args.codex_timeout,
        issue_codex_timeout=args.issue_codex_timeout,
        gh_bin=args.gh_bin,
        codex_bin=args.codex_bin,
        codex_bypass_sandbox=args.codex_bypass_sandbox,
    )


def verify_prerequisites(config: Config, runner: CommandRunner) -> None:
    """Fail early with setup instructions before a polling cycle starts."""
    try:
        runner.run(["git", "--version"])
    except AgentError as exc:
        raise AgentError(
            "Git is unavailable. Install Git and ensure 'git --version' succeeds."
        ) from exc
    try:
        runner.run([config.gh_bin, "--version"])
    except AgentError as exc:
        raise AgentError(
            f"GitHub CLI ({config.gh_bin!r}) is unavailable. Install it from "
            "https://cli.github.com/, then run 'gh auth login'."
        ) from exc
    try:
        runner.run([config.gh_bin, "auth", "status"])
    except AgentError as exc:
        raise AgentError(
            "GitHub CLI is not authenticated or its credentials are invalid. Run "
            "'gh auth login', then verify repository access with 'gh auth status'."
        ) from exc
    if config.dry_run:
        return
    try:
        runner.run([config.codex_bin, "--version"])
    except AgentError as exc:
        raise AgentError(
            f"Codex CLI ({config.codex_bin!r}) is unavailable. Install Codex, then "
            "run 'codex login'."
        ) from exc
    try:
        runner.run([config.codex_bin, "login", "status"])
    except AgentError as exc:
        raise AgentError(
            "Codex CLI is not authenticated. Run 'codex login', then confirm with "
            "'codex login status'."
        ) from exc


def main(argv: Sequence[str] | None = None) -> int:
    config = parse_args(argv)
    runner = CommandRunner()
    store = StateStore(config.state_dir)
    try:
        verify_prerequisites(config, runner)
        with store.locked():
            state = store.load()
            while True:
                try:
                    successful = process_cycle(config, runner, store, state)
                except TransientNetworkError as exc:
                    successful = False
                    LOG.warning(
                        "GitHub network remains unavailable after retries; all "
                        "unrecorded work remains pending: %s",
                        exc,
                    )
                except AgentError as exc:
                    successful = False
                    LOG.error("polling cycle failed: %s", exc)
                if config.once:
                    return 0 if successful else 1
                LOG.info("next poll in %d seconds", config.interval)
                time.sleep(config.interval)
    except AgentError as exc:
        LOG.error("%s", exc)
        return 1
    except KeyboardInterrupt:
        LOG.info("stopped")
        return 130

if __name__ == "__main__":
    sys.exit(main())
